# Generated by Django 5.0.2 on 2024-03-06 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        ('exam', '0002_remove_stage_application_date_stage_aplication_date_and_more'),
        ('library', '0004_alter_module_options_alter_question_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': ('Examen',), 'verbose_name_plural': 'Examenes'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Etapa', 'verbose_name_plural': 'Etapas'},
        ),
        migrations.RemoveField(
            model_name='stage',
            name='aplication_date',
        ),
        migrations.AddField(
            model_name='exam',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='question',
            field=models.ManyToManyField(to='library.question', verbose_name='preguntas'),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion'),
        ),
        migrations.AddField(
            model_name='stage',
            name='application_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de aplicacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='modules',
            field=models.ManyToManyField(through='exam.ExamModule', to='library.module', verbose_name='Modulos'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.stage', verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='exammodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.module', verbose_name='Modulo'),
        ),
        migrations.AlterField(
            model_name='exammodule',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='Calificacion'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage',
            field=models.IntegerField(max_length=2, verbose_name='Etapa'),
        ),
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='-', max_length=5, verbose_name='Respuesta')),
                ('correct', models.BooleanField(default='-', max_length=5, verbose_name='Correcta')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='Examen')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.question', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Desglose',
                'verbose_name_plural': 'Desglosos',
            },
        ),
    ]
